Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Gemspec/RequiredRubyVersion:
  Enabled: false

AllCops:
  SuggestExtensions: false
  NewCops: enable
